### ISSUE TITLE
Use the same connection for HTTP and Websocket messages

### ISSUE THREAD

**Issue by pliablepixels** [topaz/perl-Net-WebSocket-Server#4]
Hello, is it possible to use the same connection to listen to both HTTP and WebSocket connections while using your library?

My use-case is this:

a) I am using your lovely library to listen to port 9000 for WSS or WS for commands from clients 
b) I use your `->start()` method to run the main loop and do my work on `on_tick`

I am now interested in exposing an HTTP interface on the same port. The idea is to accept the same messages either via HTTP or WebSockets. Given the main loop is controlled by the Websocket library, is it possible for me to get control of any connections that don't get upgraded to websockets and instead of rejecting it, accept the connection and get the message?

thanks.

**Comment by topaz** [comment]
Not presently.

The [Protocol::WebSocket::Handshake::Server](https://metacpan.org/pod/Protocol%3A%3AWebSocket%3A%3AHandshake%3A%3AServer) package handles parsing the initial bytes; that entrypoint is here: https://github.com/topaz/perl-Net-WebSocket-Server/blob/master/lib/Net/WebSocket/Server/Connection.pm#L152

The initial request looks like a normal HTTP GET with some extra headers: https://en.wikipedia.org/wiki/WebSocket#Protocol_handshake

So, the best plan would probably be to defer parsing of the initial payload until after a full header had been received and then choose the right server to handle it (that is, continue parsing or hand the socket to a user-provided handler and forget it existed).  A somewhat worse alternative would be to hand all failed handshakes to such a handler with a copy of the buffer up to that point, but that involves maintaining a second copy of the buffer and the handler would receive both non-websocket HTTP requests as well as websocket requests that were invalid or failed the handshake process.

I think I prefer the first approach; if the connection's initial state is "keep buffering data until a blank line is found or an error state occurs (overflow/timeout)" and decide what to do at that point, that wouldn't be a significant change to the logic; however, it does introduce a larger surface area for bugs and security issues and it introduces potential performance issues since data would need to be parsed multiple times.

The trickier part will be what the user should do once they're handed a socket speaking regular HTTP. The goal of Net::WebSocket::Server is to be a simple, low-dependency WebSocket server.  Expecting the user to parse and route messages isn't a good experience, and HTTP frameworks don't usually have an entrypoint for "here is a connection socket".  Because I want to avoid turning Net::WebSocket::Server into a full web framework, I'm not sure if there's a good solution for this part, and that's probably my biggest issue with adding support for this.

The easiest solution for you would probably be to run an HTTP server on a second port.  The second-easiest solution would be to run a reverse proxy in front of Net::WebSocket::Server and an HTTP server that does the decision logic described above.  The best solution, though it requires more effort on your part, is to change your program to use something with all of this routing logic already available to you, like [Twiggy](https://metacpan.org/pod/Twiggy).  If you use [Plack::Builder](https://metacpan.org/pod/Plack%3A%3ABuilder) to merge an HTTP-speaking [PSGI app](https://metacpan.org/pod/PSGI#Application) (which can be a simple router or a complex Dancer webapp) and a WebSocket-speaking [Plack::App::WebSocket app](https://metacpan.org/pod/Plack::App::WebSocket), you could have a single port with two different paths that are handled by HTTP or WebSocket automatically.

**Comment by pliablepixels** [comment]
Thank for very much! I was actually thinking of something simpler - that we have an ability to intercept the message _before_ the handshake()

Something like `process_request`([ref](https://websockets.readthedocs.io/en/stable/api.html#websockets.server.WebSocketServerProtocol.process_request)) in [this websocket library](https://websockets.readthedocs.io/en/stable/api.html)

The idea here is if we get a handler before you do the handshake, I could choose to handle it and return a 2xx or 4/5xx in my handler sub in which case your library sends out that response and closes the connection. If I return nothing, then you continue with the handshake. There is no expectation here for any state/connection/route management beyond that request response for HTTP handling.

In the mean time, if I do create my own simple HTTP server, maybe using ``HTTP::Server::Simple`` what is your recommendation on handling the main loop for both? I suppose `$wss->start()` may not be the best approach?

**Comment by topaz** [comment]
This is tricky; you only know what protocol will be spoken partway through the HTTP request.

Because `Net::WebSocket::Server` doesn't know anything about the underlying protocols (that's handled by `Protocol::WebSocket::*`), it doesn't know when "before" the handshake is.  `Net::WebSocket::Server::Connection` has two states:

- The handshake parser hasn't indicated it's finished, so bytes from the socket are handed to it directly.
- The handshake parser _has_ indicated it's finished, so bytes from the socket are handed to the frame parser directly.

During this process, only `Protocol::WebSocket::*` has the partial buffer.  (This is what I was saying earlier about needing to keep a second buffer for potential later use.)

So, assuming that handshake parse errors happen on the right packets and that we have a way to differentiate regular HTTP payloads from those, `Net::WebSocket::Server::Connection` could maintain a copy of the buffer, detect this situation, hand the partial buffer and remaining socket to a user-supplied callback.  This is pretty weird, though: the user would receive some of the data as a string, but also get a socket from which they'd be responsible for reading from.  We'd also need to either change ownership of the socket to a different event polling loop or send events across to another system.  Or, if it's just a non-WebSocket-request handler that got the request, it would need to either (1) reply immediately based on the headers alone (so it would support `GET` / `HEAD` / `OPTIONS` but not `POST` / `PUT` / `PATCH` / etc) or (2) put the socket back into `Net::WebSocket::Server`'s event loop via [watch_readable](https://metacpan.org/pod/Net::WebSocket::Server#watch_readable) and wait for the rest of the message.  These problems are the sorts of things PSGI was designed to handle; it abstracts away sockets and buffers such that connection state can be passed around opaquely.  There's a chance that "only websockets or static content" is a common enough usecase that it's reasonable to support it, but it's getting dangerously far into making `Net::WebSocket::Server` do way more kinds of things than I can support.

The alternative you're describing with `HTTP::Server::Simple` is ultimately to use a different event loop, but this is weird for the same reasons with opposite responsibilities: you'd have to read a partial buffer, realize it's not the kind of header you wanted, and then say "okay `Net::WebSocket::Server`, here's a socket and some data, pretend you just `accept()`ed it, but read from the buffer before you call `read()`".  The options for dealing with this are either to add complexity to `Net::WebSocket::Server` or to try to use a filehandle package that supports multi-byte `ungetc()` like [FileHandle::Unget](https://metacpan.org/pod/FileHandle::Unget) with somewhat less logic to just fake the result of an `accept()` call.

So, I think what you'd really need is either something that can read and then re-issue the request (a reverse proxy like nginx), something that understands both protocols at once (PSGI / Twiggy), or to change the assumptions in `Net::WebSocket::Server` and an HTTP framework (rewriting parts of both).  Or, say "on a handshake error I'll give you an `HTTP::Request` of the buffer and you can decide to immediately return content or abort" with no intent to support more than header-only requests, but to me that feels like a half-solution.

**Comment by pliablepixels** [comment]
Thank you for the detailed explanation. I will, to begin with, probably look at running both the WSS server and an HTTP server on different ports and then investigate the more complete solutions like Twiggy.

When I wrote the following above:

> In the mean time, if I do create my own simple HTTP server, maybe using HTTP::Server::Simple what is your recommendation on handling the main loop for both? I suppose $wss->start() may not be the best approach?

I forgot to mention, they would be running on different ports, so the entire WSS/HTTPS shared complexity goes away. 

Thanks, and I think I can close this out.
